services:

  app:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "127.0.0.1:8000:8000"

    env_file:
      - BackEnd/.env
    volumes:
      - huggingface_cache:/root/.cache/huggingface
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant:latest

    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data:
  huggingface_cache: